services:
  api:
    image: front-bibliotheque
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
    - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes: 
      - ./database/bookshelf.sqlite:/app/database/bookshelf.sqlite
  front:
    image: front-bibliotheque
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - api