services:
  api:
    image: back-bibliotheque
    build:
      context: ./backend
      # dockerfile: Dockerfile-dev
      dockerfile: Dockerfile-multi
      target: dev
    ports: 
    - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes: 
      - ./backend/controllers/:/app/backend/
      - ./backend/models/:/app/backend/
      - ./backend/routes/:/app/backend/
      - ./backend/services/:/app/backend/
      - ./backend/app.cjs:/app/backend/app.cjs
      - ./database/bookshelf.sqlite:/app/database/bookshelf.sqlite
  front:
    image: front-bibliotheque
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - api